#!/hint/bash

# willker's dotfiles is free software: you can redistribute it and/or modify it under the terms of the 
# GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.

# willker's dotfiles is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with willker's dotfiles.
# If not, see <https://www.gnu.org/licenses/>.


OPTIONS=("${OPTIONS[@]/debug/!debug}")

CFLAGS="$(sed -E 's/(^|[[:space:]])-m(arch|tune)=[^[:space:]]+/\1/g' <<< "${CFLAGS}") -march=native"
CXXFLAGS="$(sed -E 's/(^|[[:space:]])-m(arch|tune)=[^[:space:]]+/\1/g' <<< "${CXXFLAGS}") -march=native"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
if command -v mold > /dev/null 2>&1; then
  LDFLAGS="${LDFLAGS} -fuse-ld=mold"
  RUSTFLAGS="${RUSTFLAGS} -C link-arg=-fuse-ld=mold"
fi

BUILDDIR=/tmp/makepkg

COMPRESSZST=(zstd -c -T0 --auto-threads=logical -)
