# Copyright © 2025 hiruocha

DLAGENTS=(
  'file::/usr/bin/curl -qgC - -o %o %u'
  'ftp::/usr/bin/axel -n 15 -a -o %o %u'
  'http::/usr/bin/axel -n 15 -a -o %o %u'
  'https::/usr/bin/axel -n 15 -a -o %o %u'
  'rsync::/usr/bin/rsync --no-motd -z %u %o'
  'scp::/usr/bin/scp -C %u %o'
)

BUILDENV=(!distcc color ccache check sign)

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)

PACKAGER="hiruocha <hiruocha@gmail.com>"

GPGKEY="FE3D8E6594173A0C"
