# Copyright © 2025 hiruocha

BUILDENV=(!distcc color ccache check sign)

OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)

PACKAGER="hiruocha <hiruocha@gmail.com>"

GPGKEY="FE3D8E6594173A0C"
