# This file is part of willker's dotfiles.

# willker's dotfiles is free software: you can redistribute it and/or modify it under the terms of the 
# GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.

# willker's dotfiles is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with willker's dotfiles.
# If not, see <https://www.gnu.org/licenses/>.

[shell]

[shell.files]
shell = "~/.config/shell"

[bash]
depends = ["shell"]

[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/profile" = "~/.bash_profile"

[zsh]
depends = ["shell"]

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[shell-meta]
depends = ["bash", "zsh"]

[cargo]

[cargo.files]
cargo = "~/.local/share/cargo"

[yazi]

[yazi.files]
yazi = "~/.config/yazi"

[cli-meta]
depends = ["shell-meta", "yazi"]

[pacman]

[pacman.files]
pacman = "~/.config/pacman"

[arch-meta]
depends = ["pacman"]
