# This file is part of willker's dotfiles.

# willker's dotfiles is free software: you can redistribute it and/or modify it under the terms of the 
# GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.

# willker's dotfiles is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with willker's dotfiles.
# If not, see <https://www.gnu.org/licenses/>.

[shell]

[shell.files]
"shell/aliases.sh" = "~/.config/shell/aliases.sh"
"shell/functions.sh" = "~/.config/shell/functions.sh"
"shell/profile.sh" = "~/.profile"

[bash]
depends = ["shell"]

[bash.files]
"bash/bashrc" = "~/.bashrc"

[zsh]
depends = ["shell"]

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[shell-meta]
depends = ["bash", "zsh"]

[cargo]

[cargo.files]
"cargo/config-mirror.toml" = { type = "symbolic", target = "~/.local/share/cargo/config.toml", if = '(command_success "[ -f ${XDG_STATE_HOME:-$HOME/.local/state}/need_mirror ]")' }

[npm]

[npm.files]
npm = "~/.config/npm"

[yazi]

[yazi.files]
yazi = "~/.config/yazi"

[cli-meta]
depends = ["shell-meta", "yazi", "cargo", "npm"]

[pacman]

[pacman.files]
pacman = "~/.config/pacman"

[arch-meta]
depends = ["pacman"]
