#!/hint/zsh

# willker's dotfiles is free software: you can redistribute it and/or modify it under the terms of the 
# GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.

# willker's dotfiles is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with willker's dotfiles.
# If not, see <https://www.gnu.org/licenses/>.

case "$-" in
  *i*) ;;
  *) return ;;
esac

setopt POSIX_BUILTINS

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/environment.sh" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/environment.sh"
fi
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases.sh" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases.sh"
fi
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions.sh" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/functions.sh"
fi

setopt PROMPT_SUBST
if [ -f /usr/share/git/completion/git-prompt.sh ]; then
  . /usr/share/git/completion/git-prompt.sh
  GIT_PS1_SHOWDIRTYSTATE=1
  GIT_PS1_SHOWCOLORHINTS=1
  PS1=$'[%F{magenta}%n%f@%F{yellow}%m%f]-[%F{blue}%~%f]-[%(?.%F{green}.%F{red})%?%f] $(__git_ps1 "%s") \n%(!.#.$) '
else
  PS1=$'[%F{magenta}%n%f@%F{yellow}%m%f]-[%F{blue}%~%f]-[%(?.%F{green}.%F{red})%?%f]\n%(!.#.$) '
fi

[ -d "${XDG_STATE_HOME:-$HOME/.local/state}/zsh" ] || mkdir -p "${XDG_STATE_HOME:-$HOME/.local/state}/zsh"
HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/zsh/history"
HISTSIZE=100000
SAVEHIST=100000
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE

setopt AUTOCD
setopt NUMERIC_GLOB_SORT

ZSH_PLUGINS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/zsh/plugins"

plugin() {
  for plugins_dir in "$ZSH_PLUGINS_DIR" /usr/share/zsh/plugins /usr/share/zsh/site-functions /usr/share; do
    if [ -f "$plugins_dir/$1/$1.plugin.zsh" ]; then
      . "$plugins_dir/$1/$1.plugin.zsh"
      return 0
    elif [ -f "$plugins_dir/$1/$1.zsh" ]; then
      . "$plugins_dir/$1/$1.zsh"
      return 0
    elif [ -f "$plugins_dir/$1.plugin.zsh" ]; then
      . "$plugins_dir/$1.plugin.zsh"
      return 0
    elif [ -f "$plugins_dir/$1.zsh" ]; then
      . "$plugins_dir/$1.zsh"
      return 0
    fi
  done

  return 1
}

plugin zsh-completions || true

if plugin zsh-autosuggestions; then
  ZSH_AUTOSUGGEST_STRATEGY=(history completion)
fi

command -v fzf > /dev/null 2>&1 && plugin fzf-tab || true

if plugin zsh-syntax-highlighting; then
  typeset -A ZSH_HIGHLIGHT_STYLES
  ZSH_HIGHLIGHT_STYLES[alias]='fg=magenta'
  ZSH_HIGHLIGHT_STYLES[builtin]='fg=cyan'
  ZSH_HIGHLIGHT_STYLES[function]='fg=blue'
fi

if plugin zsh-history-substring-search; then
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down
fi

unset plugins_dir
unset -f plugin

[ -d "${XDG_CACHE_HOME:-$HOME/.cache}/zsh" ] || mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
autoload -U compinit
compinit -d "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump-$ZSH_VERSION"
zstyle ':completion:*' rehash true
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompcache"
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

if command -v zoxide > /dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

if [ -f /usr/share/doc/filkoll/command-not-found.zsh ]; then
  . /usr/share/doc/filkoll/command-not-found.zsh
fi
