#!/hint/bash

# willker's dotfiles is free software: you can redistribute it and/or modify it under the terms of the 
# GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.

# willker's dotfiles is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
# PARTICULAR PURPOSE. See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with willker's dotfiles.
# If not, see <https://www.gnu.org/licenses/>.

case "$-" in
  *i*) ;;
  *) return ;;
esac

# shellcheck source=/dev/null
[ -f "$XDG_CONFIG_HOME/shell/profile.sh" ] && . "$XDG_CONFIG_HOME/shell/profile.sh"
# shellcheck source=/dev/null
[ -f "$XDG_CONFIG_HOME/shell/aliases.sh" ] && . "$XDG_CONFIG_HOME/shell/aliases.sh"
# shellcheck source=/dev/null
[ -f "$XDG_CONFIG_HOME/shell/functions.sh" ] && . "$XDG_CONFIG_HOME/shell/functions.sh"

NORMAL_PS='\[\e[m\]'
YELLOW_PS='\[\e[33m\]'
BLUE_PS='\[\e[34m\]'
MAGENTA_PS='\[\e[35m\]'
PS1="[${MAGENTA_PS}\u${NORMAL_PS}@${YELLOW_PS}\h${NORMAL_PS}]-[${BLUE_PS}\w${NORMAL_PS}]\n\$ "

[ -d "$XDG_STATE_HOME/bash" ] || mkdir -p "$XDG_STATE_HOME/bash"
HISTFILE="$XDG_STATE_HOME/bash/history"
HISTSIZE=100000
HISTFILESIZE=100000
HISTCONTROL=erasedups
shopt -s cmdhist
shopt -s histappend
PROMPT_COMMAND='history -a; history -n; '"$PROMPT_COMMAND"

# shellcheck source=/dev/null
[ -f /usr/share/bash-completion/bash_completion ] && \
[ -z "${BASH_COMPLETION_VERSINFO-}" ] && \
. /usr/share/bash-completion/bash_completion
